"""Centralized configuration for the Child Growth Monitor application."""
import os
from enum import Enum
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
UPLOAD_DIR = BASE_DIR / "uploads"
DB_PATH = BASE_DIR / "growth_monitor.db"
DATABASE_URL = f"sqlite:///{DB_PATH}"

# Authentication / JWT
JWT_SECRET = os.environ.get("CGM_JWT_SECRET", "dev-insecure-secret-change-in-production")
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_DAYS = 30

# Reference object dimensions (centimeters) - optional fallback for scale calibration
# Standard yellow packet dimensions (e.g., biscuit packet)
REFERENCE_OBJECT_LENGTH_CM = 12.7
REFERENCE_OBJECT_WIDTH_CM = 5.5
# Keep old name for backwards compatibility
PARLEG_LENGTH_CM = REFERENCE_OBJECT_LENGTH_CM
PARLEG_WIDTH_CM = REFERENCE_OBJECT_WIDTH_CM

# MediaPipe configuration
POSE_MODEL_PATH = DATA_DIR / "pose_landmarker_heavy.task"

# ML wasting detection model paths
# Generated by: python ml/train.py
ML_MODELS_DIR            = DATA_DIR / "models"
ML_WEIGHT_ESTIMATOR_PATH = ML_MODELS_DIR / "weight_estimator.keras"
ML_CLASSIFIER_PATH       = ML_MODELS_DIR / "wasting_classifier.keras"
ML_SCALER_PATH           = ML_MODELS_DIR / "feature_scaler.pkl"
ML_LABEL_ENCODER_PATH    = ML_MODELS_DIR / "label_encoder.pkl"
# TFLite versions for Android/iOS deployment
ML_WEIGHT_ESTIMATOR_TFLITE = ML_MODELS_DIR / "weight_estimator.tflite"
ML_CLASSIFIER_TFLITE       = ML_MODELS_DIR / "wasting_classifier.tflite"
POSE_MIN_DETECTION_CONFIDENCE = 0.5
POSE_MIN_PRESENCE_CONFIDENCE = 0.5

# WHO data file mappings
WHO_DATA_FILES = {
    # Lossless text packaging avoids binary-patch rejection by the PR API.
    "lhfa_0_5": DATA_DIR / "lhfa_children_0-to-5-years_lms.xlsx.b64",
    "wfh_boys_2_5": DATA_DIR / "wfh_boys_2-to-5-years_zscores.xlsx",
    "wfh_girls_2_5": DATA_DIR / "wfh_girls_2-to-5-years_zscores.xlsx",
    "wfl_boys_0_2": DATA_DIR / "wfl_boys_0-to-2-years_zscores.xlsx",
    "wfl_girls_0_2": DATA_DIR / "wfl_girls_0-to-2-years_zscores.xlsx",
}

class WastingStatus(str, Enum):
    """Canonical machine-readable wasting classification vocabulary."""

    SAM = "SAM"
    MAM = "MAM"
    NORMAL = "NORMAL"
    RISK_OVERWEIGHT = "RISK_OVERWEIGHT"
    OVERWEIGHT = "OVERWEIGHT"
    OBESE = "OBESE"
    UNKNOWN = "UNKNOWN"


WASTING_STATUS_LABELS = {
    WastingStatus.SAM: "Severe Acute Malnutrition (SAM)",
    WastingStatus.MAM: "Moderate Acute Malnutrition (MAM)",
    WastingStatus.NORMAL: "Normal",
    WastingStatus.RISK_OVERWEIGHT: "Possible Risk of Overweight",
    WastingStatus.OVERWEIGHT: "Overweight",
    WastingStatus.OBESE: "Obese",
    WastingStatus.UNKNOWN: "Unknown",
}

_LEGACY_WASTING_STATUSES = {
    label: status for status, label in WASTING_STATUS_LABELS.items()
}


def canonicalize_wasting_status(value):
    """Convert persisted legacy labels at migration/deserialization boundaries."""
    if value is None:
        return None
    try:
        return WastingStatus(value)
    except ValueError:
        try:
            return _LEGACY_WASTING_STATUSES[value]
        except KeyError as exc:
            raise ValueError(f"Unrecognized wasting status: {value!r}") from exc

# Classification thresholds (WHO standard)
CLINICAL_MIN_AGE_MONTHS = 0
CLINICAL_MAX_AGE_MONTHS = 60  # Exclusive: WHO tables cover birth through 59 months.

# Poshan Setu v1 programme thresholds. Each BMI tuple is
# (SAM upper bound, Normal lower bound); values between them are MAM.
POSHAN_BMI_THRESHOLDS = {
    "M": (13.0, 13.7),
    "F": (12.8, 13.5),
}
POSHAN_MUAC_SAM_MAX_CM = 11.5
POSHAN_MUAC_NORMAL_MIN_CM = 12.5
POSHAN_MUAC_MIN_AGE_MONTHS = 6.0
POSHAN_MUAC_MAX_AGE_MONTHS = 60.0

ZSCORE_CLASSIFICATIONS = {
    "haz": {
        (-99, -3): "Severely Stunted",
        (-3, -2): "Stunted",
        (-2, 2): "Normal",
        (2, 99): "Tall",
    },
    "whz": {
        (-99, -3): WastingStatus.SAM,
        (-3, -2): WastingStatus.MAM,
        (-2, 1): WastingStatus.NORMAL,
        (1, 2): WastingStatus.RISK_OVERWEIGHT,
        (2, 3): WastingStatus.OVERWEIGHT,
        (3, 99): WastingStatus.OBESE,
    },
}

# ============================================================
# ANTHROPOMETRIC RATIOS FOR HEIGHT ESTIMATION
# ============================================================
# Based on pediatric anthropometry literature.
# These ratios represent typical body segment proportions as fractions of total height.
# 
# Sources:
# - WHO Child Growth Standards
# - Roche AF, Davila GH. "Late adolescent growth in stature"
# - Fredriks AM et al. "Body index measurements in 1996-7 compared with 1980"

# Ratios by age group (segment length as fraction of total height)
ANTHROPOMETRIC_RATIOS = {
    # Infants 0-12 months: larger head relative to body
    "0-12_months": {
        "head_ratio": 0.28,   # Head is ~28% of height
        "torso_ratio": 0.32,  # Torso ~32%
        "leg_ratio": 0.40,    # Legs ~40%
    },
    # Toddlers 12-24 months: head proportion decreasing
    "12-24_months": {
        "head_ratio": 0.25,
        "torso_ratio": 0.32,
        "leg_ratio": 0.43,
    },
    # Young children 24-48 months
    "24-48_months": {
        "head_ratio": 0.22,
        "torso_ratio": 0.30,
        "leg_ratio": 0.48,
    },
    # Children 48-60 months: closer to adult proportions
    "48-60_months": {
        "head_ratio": 0.20,
        "torso_ratio": 0.30,
        "leg_ratio": 0.50,
    },
}

# Function to get ratios for a specific age
def get_anthropometric_ratios(age_months: float) -> dict:
    """Get body segment ratios for a given age in months."""
    if age_months < 12:
        return ANTHROPOMETRIC_RATIOS["0-12_months"]
    elif age_months < 24:
        return ANTHROPOMETRIC_RATIOS["12-24_months"]
    elif age_months < 48:
        return ANTHROPOMETRIC_RATIOS["24-48_months"]
    else:
        return ANTHROPOMETRIC_RATIOS["48-60_months"]

# Measurement validation thresholds
HEIGHT_VALIDATION_SD = 3.0  # Flag if height is >3 SD from WHO median
SEGMENT_AGREEMENT_THRESHOLD = 0.15  # Max 15% difference between segment-based estimates
MIN_CONFIDENCE_THRESHOLD = 0.5  # Minimum pose confidence to use measurement

# Expected height ranges by age (cm) - for sanity checking
# Based on WHO growth charts (approximately -3 SD to +3 SD)
HEIGHT_RANGES_BY_AGE = {
    (0, 6): (45, 75),      # 0-6 months
    (6, 12): (60, 85),     # 6-12 months
    (12, 24): (70, 95),    # 12-24 months
    (24, 36): (80, 105),   # 24-36 months
    (36, 48): (85, 115),   # 36-48 months
    (48, 60): (95, 125),   # 48-60 months
}
