import 'package:drift/drift.dart';
import 'visits_table.dart';

class Measurements extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get visitId => integer().unique().references(Visits, #id)();
  RealColumn get predictedHeightCm => real().nullable()();
  RealColumn get predictedWeightKg => real().nullable()();
  RealColumn get manualHeightCm => real().nullable()();
  RealColumn get manualWeightKg => real().nullable()();
  RealColumn get effectiveHeightCm => real().nullable()();
  RealColumn get effectiveWeightKg => real().nullable()();
  TextColumn get heightMethod => text().nullable()();
  TextColumn get weightMethod => text().nullable()();
  RealColumn get bmi => real().nullable()();
  TextColumn get bmiStatus => text().nullable()();
  RealColumn get hazZscore => real().nullable()();
  RealColumn get whzZscore => real().nullable()();
  TextColumn get hazStatus => text().nullable()();
  TextColumn get whzStatus => text().nullable()();
  RealColumn get confidenceScore => real().nullable()();
  RealColumn get heightConfidence => real().nullable()();
  RealColumn get weightConfidence => real().nullable()();
  RealColumn get classificationConfidence => real().nullable()();
  TextColumn get bodyBuild => text().nullable()();
  TextColumn get estimationMethod => text().nullable()();
  BoolColumn get sideViewUsed => boolean().withDefault(const Constant(false))();
  RealColumn get chestDepthCm => real().nullable()();
  RealColumn get abdDepthCm => real().nullable()();
  RealColumn get mlEstimatedWeightKg => real().nullable()();
  RealColumn get samProbability => real().nullable()();
  RealColumn get mamProbability => real().nullable()();
  RealColumn get normalProbability => real().nullable()();
  RealColumn get riskOverweightProbability => real().nullable()();
  RealColumn get overweightProbability => real().nullable()();
  TextColumn get wastingStatus => text().nullable()();
  TextColumn get wastingMethod => text().nullable()();
  RealColumn get muacCm => real().nullable()();
  TextColumn get muacStatus => text().nullable()();
  TextColumn get muacMethod => text().nullable()();
  BoolColumn get muacAgeInRange => boolean().nullable()();
  RealColumn get muacConfidence => real().nullable()();
  RealColumn get muacUncertaintyLowerCm => real().nullable()();
  RealColumn get muacUncertaintyUpperCm => real().nullable()();
  TextColumn get muacModelVersion => text().nullable()();
  TextColumn get muacCalibrationVersion => text().nullable()();
  BoolColumn get muacIsDirectMeasurement => boolean().nullable()();
  BoolColumn get muacRequiresConfirmation => boolean().nullable()();
  TextColumn get muacReferralGuidance => text().nullable()();
  TextColumn get combinedStatus => text().nullable()();
  TextColumn get combinedTriggeredBy => text().nullable()();
  TextColumn get combinedRationale => text().nullable()();
  TextColumn get combinedMethod => text().nullable()();
  RealColumn get combinedConfidenceScore => real().nullable()();
  TextColumn get combinedProtocolVersion => text().nullable()();
}
